const ERROR_CODES = {
  // General
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  CONFLICT: "CONFLICT",

  // Authentication
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_SIGNATURE: "INVALID_SIGNATURE",
  INVALID_NONCE: "INVALID_NONCE",
  NONCE_EXPIRED: "NONCE_EXPIRED",
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",

  // Users
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  INVALID_USER_DATA: "INVALID_USER_DATA",

  // Markets
  MARKET_NOT_FOUND: "MARKET_NOT_FOUND",
  MARKET_UNAVAILABLE: "MARKET_UNAVAILABLE",

  // Trading
  INVALID_TRADE: "INVALID_TRADE",
  INVALID_TRADE_AMOUNT: "INVALID_TRADE_AMOUNT",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  INSUFFICIENT_ALLOWANCE: "INSUFFICIENT_ALLOWANCE",
  INVALID_TOKEN_PAIR: "INVALID_TOKEN_PAIR",
  INVALID_SLIPPAGE: "INVALID_SLIPPAGE",
  QUOTE_FAILED: "QUOTE_FAILED",
  TRADE_FAILED: "TRADE_FAILED",
  TRADE_NOT_FOUND: "TRADE_NOT_FOUND",
  TRADE_EXPIRED: "TRADE_EXPIRED",

  // Portfolio
  PORTFOLIO_NOT_FOUND: "PORTFOLIO_NOT_FOUND",
  BALANCE_FETCH_FAILED: "BALANCE_FETCH_FAILED",

  // Oracle / Price
  PRICE_FETCH_FAILED: "PRICE_FETCH_FAILED",
  PRICE_UNAVAILABLE: "PRICE_UNAVAILABLE",
  STALE_PRICE: "STALE_PRICE",

  // Blockchain
  BLOCKCHAIN_ERROR: "BLOCKCHAIN_ERROR",
  BLOCKCHAIN_UNAVAILABLE: "BLOCKCHAIN_UNAVAILABLE",
  TRANSACTION_FAILED: "TRANSACTION_FAILED",
  TRANSACTION_REVERTED: "TRANSACTION_REVERTED",
  TRANSACTION_NOT_FOUND: "TRANSACTION_NOT_FOUND",
  TRANSACTION_PENDING: "TRANSACTION_PENDING",
  TRANSACTION_TIMEOUT: "TRANSACTION_TIMEOUT",
  CONTRACT_ERROR: "CONTRACT_ERROR",
  CONTRACT_NOT_FOUND: "CONTRACT_NOT_FOUND",
  WALLET_ERROR: "WALLET_ERROR",
  INSUFFICIENT_GAS: "INSUFFICIENT_GAS",
  NETWORK_ERROR: "NETWORK_ERROR",

  // Token
  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
  TOKEN_TRANSFER_FAILED: "TOKEN_TRANSFER_FAILED",
  TOKEN_APPROVAL_FAILED: "TOKEN_APPROVAL_FAILED",
  INVALID_TOKEN_ADDRESS: "INVALID_TOKEN_ADDRESS",

  // DEX
  DEX_ERROR: "DEX_ERROR",
  DEX_UNAVAILABLE: "DEX_UNAVAILABLE",
  SWAP_FAILED: "SWAP_FAILED",
  LIQUIDITY_UNAVAILABLE: "LIQUIDITY_UNAVAILABLE",

  // Vault
  VAULT_ERROR: "VAULT_ERROR",
  VAULT_DEPOSIT_FAILED: "VAULT_DEPOSIT_FAILED",
  VAULT_WITHDRAW_FAILED: "VAULT_WITHDRAW_FAILED",

  // External Services
  EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
  EXTERNAL_SERVICE_UNAVAILABLE: "EXTERNAL_SERVICE_UNAVAILABLE",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
};

export default ERROR_CODES;
